name: "lint - format - types"
on: push
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js 18
              uses: actions/setup-node@v2
              with:
                  node-version: 18
            - name: install dependencies
              run: yarn
            - name: format
              run: yarn run format:check
            - name: lint
              run: yarn run lint:check
            # - name: check types
            #   run: yarn run types:check